### ISSUE TITLE
Variable Drop Down Menus

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#100]
Every time we are selecting variables from a pre-populated list (drop down menu), the options should concatenate the variable name and the variable code. A dash or a colon could be used.

![image](https://cloud.githubusercontent.com/assets/5023186/8071686/a42c316c-0ec9-11e5-86c5-13931cb5e3c7.png)

**Comment by marioscience** [comment]
This change is done.

**Comment by AmberSJones** [comment]
Great.
