### ISSUE TITLE
Consistent Naming

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#102]
There are several places where the names of tables and forms are inconsistent. We should use the terminology in the schema to the extent possible. Here are some examples:

Shouldn't use Sensor Output Variables- it's Instrument Output Variables
![image](https://cloud.githubusercontent.com/assets/5023186/8071754/30773b80-0eca-11e5-9a12-0bffe5659e8c.png)
Vendors: Should be Organizations
![image](https://cloud.githubusercontent.com/assets/5023186/8071783/7642edc6-0eca-11e5-89ac-358315e1cb2c.png)
'Event' should be Action
![image](https://cloud.githubusercontent.com/assets/5023186/8071819/f837d0c6-0eca-11e5-8c4f-5c0a6d5b6fa4.png)

**Comment by marioscience** [comment]
I made these changes and tried to change any terminology that I thought should change. Should Field Activities be changed to Actions?

**Comment by AmberSJones** [comment]
Vendors should be changed to Organizations in the tab and on the 'New' button.
![image](https://cloud.githubusercontent.com/assets/5023186/8365573/2ad893c6-1b4b-11e5-8c30-41599e20586a.png)

I'm not seeing 'Field Activity' anywhere. Is it still somewhere on the site?

**Comment by marioscience** [comment]
I made this change. Field activities were thoroughly changed on all instances that I found (using PyCharm) so there shouldn't be anymore left.

**Comment by AmberSJones** [comment]
Great.
