### ISSUE TITLE
EndDateTime should auto-populate

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#105]
For all actions on the Add Site Visit form, the EndDateTime needs to auto-populate:
- For the parent site visit, it should populate with the BeginDateTime.
- For all of the children actions, the EndDateTime should populate with the EndDateTime of the parent Site Visit.

**Comment by marioscience** [comment]
These features were added to the site visit form and nested action forms.

**Comment by AmberSJones** [comment]
I'm not getting the SiteVisit EndDateTime to auto-populate with the BeginDateTime after I change the BeginDateTime.

The date times for the children activities are auto-populating correctly.

**Comment by marioscience** [comment]
The way I set up the EndDateTime to be populated is first from BeginDateTime and then the date is unchanged if it is set by the user (unless the that datetime is after the datetime is already set, in which case is then updated). If I understand correctly, every time the BeginDateTIme is set/changed the EndDateTime should be updated with the same datetime? What about nested actions, should the datetimes be updated on those fields when the parent BeginDateTime changes?

**Comment by AmberSJones** [comment]
You're right- the EndDateTime should populate from the BeginDateTime, and it should change to reflect any changes made by the user in the BeginDateTime. 

For nested actions, yes, I think the datetimes should change to reflect what the user updates on the parent action.

Ideally, the user only sets the BeginDateTime for the parent action once so that the parent EndDateTime and datetimes for child actions only change once, but of course there are cases where the user will go back and re-enter it. So, I think the rule is that they always change to reflect what the user enters. Perhaps we should have a note to specify that. I'll think about it.

**Comment by marioscience** [comment]
I believe the desired behavior is implemented. Please let me know if it works as expected.

**Comment by AmberSJones** [comment]
This seems good to me. Closing.
