### ISSUE TITLE
Add Site Visit- Editing of Time

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#106]
The times are difficult to edit- can we implement something that uses the keyboard arrows to change the HH:MM:SS?

**Comment by jcaraballo17** [comment]
Is this still necessary? right now we are using a calendar widget to select the date and then the time, and it seems pretty easy to do for me. What do you think @AmberSJones?

**Comment by AmberSJones** [comment]
I see the clock in the calendar widget, which I hadn't noticed before. It is problematic for the following reasons:
- it is small
- the widget goes away when the date is selected
- the widget goes away when an arrow is clicked even once (this makes it not functional)

We need an easy way to edit the times. We need to minimize mouse clicks, so this would be better done from the keyboard. Ideally, we should be able to:
1. Select date from a calendar widget for the Begin Date Time
2.  Automatically highlight the time, which can be adjusted using the keyboard
3.  Automatically move to editing editing the End Date Time. using #1 and #2.

**Comment by AmberSJones** [comment]
This is much improved. There are probably other ways to make it more streamlined, but I'm ready to put it in the technicians' hands and see if they are ok with it.
