### ISSUE TITLE
Add Site Visit form: Restrict Equipment available for selection

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#107]
For actions nested under a site visit, we need to restrict the equipment available for selection to the equipment that is deployed at that site. This is appropriate for Calibrations, Maintenance, and Generic Actions. Deployment can be any equipment.

**Comment by marioscience** [comment]
This is implemented for the Equipment Used field. What about Reference Equipment under calibration actions, should that field be filtered as well?

**Comment by AmberSJones** [comment]
I'll test this is a bit, but to answer your question- no, reference equipment should allow the selection of any equipment in the database.

**Comment by AmberSJones** [comment]
I see that the equipment is being restricted, but I don't think that the restriction is occurring properly- the Equipment that I see available are not the Equipment deployed at that site. Here is an example:
![image](https://cloud.githubusercontent.com/assets/5023186/8802182/eed950ea-2f7c-11e5-8c7e-89fb67076b3f.png)
Yet what is deployed at that site:
![image](https://cloud.githubusercontent.com/assets/5023186/8802190/0024a5de-2f7d-11e5-899e-0c0228c234dc.png)

**Comment by AmberSJones** [comment]
This appears to be addressed. Closing.
