### ISSUE TITLE
Add Site Visit form: Add Calibration Reference Materials and Equipiment

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#110]
When adding a calibration to an add site visit, we need to be able to add calibration standards and calibration reference equipment.

**Comment by marioscience** [comment]
I added the ability to select reference materials and create calibration standards. Does this suffice for calibration standards? I will implement something similar for calibration reference equipment.

**Comment by marioscience** [comment]
Calibration Reference Equipment can be selected from a multiple select input.

**Comment by AmberSJones** [comment]
Yes, this is good. The only issue outstanding is that I can't differentiate between calibration standards of the same type/value, so I think we need to include some additional fields for the selection of a calibration reference material. What are you currently displaying?

**Comment by marioscience** [comment]
Right now I am showing ReferenceMaterialID and ReferenceMaterialMediumCV.

**Comment by AmberSJones** [comment]
Let's use ReferenceMaterialMediumCV, ReferenceMaterialCode, and ReferenceMaterialLotCode.

Does it make sense to also include the ReferenceMaterialValue or is this not needed since you will implement a check on the Variable as discussed in issue #103 ?

**Comment by jcaraballo17** [comment]
Changed the string to display
"ReferenceMaterialMediumCV : ReferenceMaterialCode ReferenceMaterialLotCode"

**Comment by AmberSJones** [comment]
We also need to select the ReferenceMaterialValue somehow. This is probably most directly done via multiple entries in the Calibration Standards field. So, we may also need to include the reference material value, the variable name, and the units. That will involve a lot of joins...

But I'm thinking that we need to display:
ReferenceMaterialMediumCV: ReferenceMaterialCode ReferenceMaterialLotCode: VariableName ReferenceMaterialValue Units Abbreviation

**Comment by AmberSJones** [comment]
Just need to add the ReferenceMaterialValue field from the ReferenceMaterialValues table.

**Comment by AmberSJones** [comment]
Great, closing.
