### ISSUE TITLE
Add Site Visit form: Equipment Information

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#111]
When displaying information on equipment for selection on the actions nested under the Add Site Visit, we need to display the Equipment Type and Model along with the Equipment Code and Serial Number. It might get long, but it will be very clear what equipment is available for selection.

**Comment by marioscience** [comment]
Added type and model in parenthesis for each equipment.

**Comment by AmberSJones** [comment]
This is good. Closing.
