### ISSUE TITLE
Implement Retrievals

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#116]
We need to implement 'Retrievals'. A retrieval is an action and should be implemented under the Add Site Visit page as well as with an independent add/edit page. A retrieval action should be related to a deployment action using the related actions table and the 'isRetrievalof' as the RelationshipTypeCV. A retrieval effectively ends the deployment of a particular piece of equipment at a particular site.

**Comment by AmberSJones** [comment]
1. Instrument deployment actions should initially have no end date.
2. An instrument retrieval ends an instrument deployment (and creates the end date for an instrument deployment). The user needs to be able to select the deployment action that the retrieval is ending.
3. A related action needs to be created to relate the retrieval to the deployment that it is ending (isRetrievalof).

We need a specialized form for retrievals- a standalone form and a nested action form that include the selection of the deployment that the retrieval is ending.
On the Deployments table, we need to distinguish active deployments from inactive by color and/or sorting (add a column to the table).

**Comment by ZachYoshikawa** [comment]
Retrieval Form input
- dateTime (required)
- Select a method (instrumentRetrieval or equipmentRetrieval) (required)
- Action description (optional)

**Comment by AmberSJones** [comment]
We resolved to select a deployment and then use the 'Retrieve' button rather than create a retrieval action and then select the deployment. We could implement the latter option at a later date if desired.

**Comment by AmberSJones** [comment]
We need to create 1. an independent retrieval form called by the 'Retrieve' button, and 2. a retrieval form under the Site Visit form, which will require the user to select a deployment to retrieve. For the deployment, the fields that should be displayed are: StartDateTime, SiteCode, EquipmentSerialNumber, EquipmentType, ManufacturerName, ModelPartNumber.

**Comment by AmberSJones** [comment]
I'm closing this issue. Retrievals appear to be functional- any issues that may crop up are smaller and should be posted separately.
