### ISSUE TITLE
Implement Results Generation

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#117]
We need to implement the generation of records in the Results table when an Action of type 'InstrumentDeployment' is created. So, the user would need to be prompted about the selection or creation of Variables and InstrumentOutputVariables when an InstrumentDeployment occurs.

**Comment by AmberSJones** [comment]
User will need to select Variable/InstrumentOutputVariable, Units, ProcessingLevel, SampledMediumCV.

ResultDateTime and ResultDateTimeUTCOffset = those of the deployment action
ValueCount = 0
StatusCV = ongoing (check the CV)
Result UUID = need to create as a GUID
ResultTypeCV = Time Series Coverage (check the CV)

**Comment by AmberSJones** [comment]
We need one view (a list of results) and one form (creation of results).

For the form, it is as described in the above comment.

For the view, we should display: Site Code, Site Name, VariableCode, Variable Name, BeginDateTime, ResultType, ResultDateTime. Requires a few joins, but shouldn't be too complicated.

**Comment by jcaraballo17** [comment]
This is finally done.

**Comment by AmberSJones** [comment]
This is all great! A few things outstanding:

- The form needs to be implemented for the 'Create Deployment Action' also:
![image](https://cloud.githubusercontent.com/assets/5023186/12593228/3737dbbe-c42d-11e5-8c6b-c5c49427256a.png)

- We need to filter the possible InstrumentOutputVariables based on the equipment selected (link on ModelID):
![image](https://cloud.githubusercontent.com/assets/5023186/12593070/6b11321a-c42c-11e5-9d60-998b0464bd7a.png)

- Can we add a summary of the Result generation on the Site Visit Summary page?
![image](https://cloud.githubusercontent.com/assets/5023186/12593162/e0eff28c-c42c-11e5-9f7b-c86e8b9a3210.png)

**Comment by jcaraballo17** [comment]
The selection of Equipment Used now filters the Instrument Output Variables and the Units.

**Comment by AmberSJones** [comment]
Great! I'm closing.
