### ISSUE TITLE
Implement Action Annotations

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#118]
We are using Action Annotations to describe environmental conditions when an Action was performed. We need to display these on the Site Visit page and implement the ability to add an annotation with a site visit.

Really, a user should be able to add an annotation to any action, but I'm thinking we only implement it for site visits at this point.

**Comment by AmberSJones** [comment]
This is great. The only issue with the implementation- when trying to edit a site visit to which an annotation has been added, the annotations associated with the action are not edit-able.

**Comment by jcaraballo17** [comment]
Closing this and moving this problem to issue #153.
