### ISSUE TITLE
Text label changes in forms

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#125]
New Site Page:
- [x] Change Elevation to 'Elevation (m)'
- [x] Change Latitude and Longitude to 'Latitude (dec deg)' and 'Longitude (dec deg)'

Create Calibration Standard:
- [x] Change Variables to 'Variable'

Create New Organization
- [x] Change to 'Create Organization' rather than 'Create Vendor'

**Comment by ZachYoshikawa** [comment]
These fixes are under the branch 'textLabelChanges'

**Comment by ZachYoshikawa** [comment]
Re-implemented changes in 'letterChanges' branch.

**Comment by ZachYoshikawa** [comment]
Also, attempting to create a site has an IntegrityError for the SQL database that should probably be a separate issue.

**Comment by AmberSJones** [comment]
Yes @ZachYoshikawa , please add it as an issue!

**Comment by ZachYoshikawa** [comment]
@AmberSJones I will add the issue tomorrow morning.

**Comment by ZachYoshikawa** [comment]
@AmberSJones @jcaraballo17 Juan told me that it had to do with him reorganizing SQL database and that he took care of it. I tested it and it is fixed.

**Comment by ZachYoshikawa** [comment]
@jcaraballo17 Ready to be merged with master branch and pushed to sandbox server.

**Comment by AmberSJones** [comment]
Great, closing.
