### ISSUE TITLE
Add correct associations fields instead of text fields in forms

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#126]
New Site Page:
- [x] SiteType
- [x] ElevationDatum
- [x] GeoType

Create Equipment:
- [x] Equipment Type

Create Factory Service:
- [x] Show same text for Equipment as in the Site Visit form

Create Equipment Model:
- [x] Implement file selection of the 'Specifications File'

Create Calibration Standard:
- [x] Add Accuracy
- [x] Add ability to load a certificate file for ReferenceMaterialCertificateLink

Create New Organization:
- [x] Organization Type

**Comment by jcaraballo17** [comment]
This is pretty complicated, I'll take on this one.

**Comment by ZachYoshikawa** [comment]
Okay, sounds good.

**Comment by AmberSJones** [comment]
Great, closing.
