### ISSUE TITLE
500 Error when adding an Equipment

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#127]

**Comment by jcaraballo17** [comment]
This error occurs when trying to set an Equipment Type that doesn't exist in the database. This issue will be resolved after completing issue #126.

**Comment by jcaraballo17** [comment]
Read issue #128.

**Comment by AmberSJones** [comment]
@jcaraballo17 - not sure if you've actually fixed this issue or not, but I'm still getting the 500 error when adding equipment. Maybe you just haven't pushed your changes to the sandbox server?

**Comment by jcaraballo17** [comment]
@AmberSJones I haven't pushed it yet, but this was happening because of issue #128 and it's resolved.
