### ISSUE TITLE
Create foreign key fields for CVs

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#128]
Since the controlled vocabularies were added to the database, the cv fields in other tables are now foreign keys and those changes were not reflected on the application models. Any object with a cv field (Sites, Equipment, etc.) will crash because of the database constraint. This is what's happening with issue #127 and issue #126 depends on that too.

@AmberSJones when changes are made to the database, can we get a list of what those changes are so we can do the same to the models?

**Comment by jcaraballo17** [comment]
Added all the foreign key fields to the models.

**Comment by AmberSJones** [comment]
@jcaraballo17 - I will keep you updated on any changes being made to the database. I know @marioscience knew about these changes, but obviously didn't get the models updated.  Thanks for catching this.
