### ISSUE TITLE
Move buttons above tables

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#129]
On many pages, there are buttons below the table in the bottom half of the page. If the table gets long, it pushes the buttons too low on the page. We need to move the buttons up to keep them accessible. 

For example, on the Site Details page:
![image](https://cloud.githubusercontent.com/assets/5023186/10521055/d52dd232-732a-11e5-806c-4f2e66cef013.png)

**Comment by ZachYoshikawa** [comment]
@AmberSJones @jcaraballo17 This fix is in branch ODM2Sensor-129

**Comment by AmberSJones** [comment]
@jcaraballo17 @ZachYoshikawa , when resolution on issues is pushed to the sandbox server, mark it as ready for testing and let me know. Thanks!

**Comment by ZachYoshikawa** [comment]
@jcaraballo17 Ready to be merged with master branch and pushed to sandbox server.

**Comment by AmberSJones** [comment]
Great, closing.
