### ISSUE TITLE
Position of Stars to Indicate Required Fields

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#131]
We are using stars to indicate whether a field is required or not. These were previously placed on the outside of the box, but now they started appearing on the inside. Can we move them to the outside of the entry boxes?
![image](https://cloud.githubusercontent.com/assets/5023186/10521195/ad33987e-732b-11e5-800f-b7ec132819e7.png)

**Comment by jcaraballo17** [comment]
I think @ZachYoshikawa solved this, assigned just to be sure.

**Comment by ZachYoshikawa** [comment]
Issue fixed on issue #129 branch. @jcaraballo17 Need to merge django branch to master tomorrow and push to sandbox server for testing.

**Comment by AmberSJones** [comment]
When at full width, this appears to be fixed, but the issue is still there when the window is resized to a smaller width:
![image](https://cloud.githubusercontent.com/assets/5023186/10983727/89102fc8-83d1-11e5-9b9d-58ad062c19d0.png)

**Comment by AmberSJones** [comment]
Great, closing.
