### ISSUE TITLE
Selecting Site Visit- Field to Display

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#133]
On the Create Action forms (Create Deployment Action, Create Calibration Action, Create Generic Action), when selecting a Site Visit for the Action, the fields currently displayed are BeginDate, EndDate, and ActionDescription for the Site Visit Action. The fields that should be displayed are: BeginDateTime and SamplingFeatureCode. I think that will be sufficient.

**Comment by ZachYoshikawa** [comment]
@jcaraballo17 Site Visit does not have a model that contains begindatetime and samplingfeaturecode in one class. This data is contained in the classes Action() and SamplingFeature() respectively in models.py. Do I need to make a new model to make the query work in the SiteVisitChoiceField() class in forms.py?

**Comment by AmberSJones** [comment]
Great.
