### ISSUE TITLE
Restrict Equipment on Create Action pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#134]
When creating an Action (Calibration Action, or Generic Action), once a Site Visit is selected, the Equipment available for selection should be restricted to the Equipment deployed at that site during that time period.

**Comment by AmberSJones** [comment]
Should be able to select multiple pieces of equipment.

Need to have access to the list of equipment currently deployed at the site or the full list of equipment. This could be a radio button to specify a filter or two separate select boxes.

**Comment by AmberSJones** [comment]
There are a few questions/issues here:

1. The restricted equipment list has duplicates:
![image](https://cloud.githubusercontent.com/assets/5023186/11629702/ead03c46-9cb6-11e5-8b72-df0832365716.png)

2. When the 'Show all equipment' check box is toggled, it doesn't always work as expected. I think you have to click in the 'Equipment Used' box again to get the 'Show all equipment' to work as expected.

**Comment by jcaraballo17** [comment]
I used a filtering function that was already there, but apparently it have some issues and gives duplicated results. I just checked the function and it is getting the site in which a particular site visit was done, and returning all the pieces of equipment that are deployed there. 
Is this what we want? Or should it display just the equipment used in that site visit?

**Comment by AmberSJones** [comment]
You're right- we want to display all of the equipment deployed at the site at the time the site visit occurred. But this shouldn't result in duplicates...

**Comment by jcaraballo17** [comment]
Figured out why there were duplicates, and fixed query to return the equipment that was deployed at the site at the moment the site visit occurred.

**Comment by AmberSJones** [comment]
The duplicates are addressed- I think that the query that filters the equipment is working. However, the 'Show all equipment' button is not functional.

**Comment by jcaraballo17** [comment]
The 'Show all equipment' button is working, it just takes some time to load all the equipments. I'll refactor it when I finish the issue I'm working on right now.

**Comment by jcaraballo17** [comment]
Show all equipment button works faster now.

**Comment by AmberSJones** [comment]
Great! Closing.
