### ISSUE TITLE
Restrict DateTimes on Create Action pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#135]
When creating an Action (Deployment Action, Calibration Action, or Generic Action), once a Site Visit is selected, the DateTimes should be populated to the BeginDateTime and EndDateTime for that Site Visit as well as be restricted to fall within those date times (similar to the restriction on the nested Action page). See below for current behavior.

![image](https://cloud.githubusercontent.com/assets/5023186/10522519/c9c9c3ee-7332-11e5-85b1-60a2e5a8fb51.png)

**Comment by AmberSJones** [comment]
This is great, but the new action start date is being set to the site visit end date time instead of the site visit begin date time.
![image](https://cloud.githubusercontent.com/assets/5023186/11629265/5a2fe77e-9cb4-11e5-9bd8-fcf471be3e95.png)

**Comment by AmberSJones** [comment]
Update: when you de-select a site visit and then re-select it, both the begin and end date times change to the site visit begin date time.

**Comment by jcaraballo17** [comment]
It should work now.

**Comment by AmberSJones** [comment]
This is so close. But if I select a different site visit from the original selection, the begin date time changes  correctly, but the end date time still corresponds to the first site visit selected.
![image](https://cloud.githubusercontent.com/assets/5023186/11639776/0036200c-9cec-11e5-8577-ce5722300c6e.png)

**Comment by jcaraballo17** [comment]
That site visit starts at 11am and ends at 3am. Since the endtime is before the begintime it's making the datetimepicker crash.
Should I just ignore the endtime when that happens? Or set the endtime to be the begintime and vice-versa?

**Comment by AmberSJones** [comment]
Oooh, I see- the end date time for that site visit is before the begin date time for the site visit. I'm going to try to correct those cases in the database- that should not be happening. I'm guessing it's an am/pm issue in this case.

To prevent this, for the web interface, let's set the end time to be the begin date time. The begin date time should always be maintained.

 In fact, we should probably implement business rules in the ODM2 schema to prevent that- can we do that @horsburgh ?

**Comment by horsburgh** [comment]
Yes - it can likely be done as a database constraint.  But, given that constraints are created differently in different RDBMS, I think it would best to just handle it in the application for now.  It may come back to haunt me later...

**Comment by jcaraballo17** [comment]
It is restricted in the web interface. When you are creating a site visit and select a begin date, the end date is set to that begin date and you can't select a data before that one.

**Comment by AmberSJones** [comment]
Ok- I've adjusted all of these in the production database, so they might now reflect in the interface yet depending on which database you are using, @jcaraballo17.

**Comment by AmberSJones** [comment]
I'm going to close the issue- I think it's resolved.
