### ISSUE TITLE
Calibration Standard Action

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#136]
@AmberSJones right now all the fields in the form to create a calibration standard are from Reference Material and Reference Material Values, but I'm looking at the database and a Calibration Standard has a field referencing an Action.
What should I do with that? Should I include the form to create an action on the calibration standard form? I don't know where to get that data from.

**Comment by AmberSJones** [comment]
No- the calibration standard itself (that is, the reference material- we can use those terms more or less interchangeably) stands alone without any action. The 'CalibrationStandards' table is a bridge table to link an Action to a ReferenceMaterial. Does that make sense? So, any Action that is of type 'Calibration' should have the option of selecting a calibration standard/reference material.

**Comment by jcaraballo17** [comment]
So, the list of Calibration Standards in Vocabularies -> Calibration should really be reference materials?

As it is right now, it shows the calibration standards (the bridge table between action and reference material), so when you click on 'new calibration standard' you are really creating a reference material and nothing shows up in the table. When you go back to the list, it looks like the new calibration standard was not created.

**Comment by AmberSJones** [comment]
Yes, it should refer to the reference materials table. Does that clear things up? Let me know if you have other questions on this.

**Comment by jcaraballo17** [comment]
Yeah, it makes sense now. Thanks!
