### ISSUE TITLE
Reorganize the Vocabularies Pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#139]
The Vocabularies pages need to be reorganized. We should put all of the 'Types' together (the un-editable tables) as Vocabularies.

Then we need to consider how to display the other tables (and which tables to display). Some of these have their own links already:
Equipment (already linked from the menu)
EquipmentModels (already linked from the menu)
InstrumentOutputVariables (already linked from the menu)
People
Organizations
CalibrationStandards
Methods

We can discuss this as a group sometime.

**Comment by AmberSJones** [comment]
Resolved: Put all of the CVs on one tab called Vocabularies with the list of un-editable vocabularies in the menu. Each should have its own page.

Put 'People' and 'Organizations' on a new tab called 'People'.
Add 'Methods' and 'Calibration Standards' to the 'Actions' tab.

**Comment by AmberSJones** [comment]
This is fantastic! Only question- I know it might seem odd to have People under the People menu- but can we do it? 'Humans' is ok, but I think we should be consistent with the data model terminology.
![image](https://cloud.githubusercontent.com/assets/5023186/11629061/061d9506-9cb3-11e5-923d-f5de80bcddab.png)

**Comment by ZachYoshikawa** [comment]
Haha, I didn't think you would go for the Humans, but it was worth a shot! ^_^ I'll change it tonight.

**Comment by AmberSJones** [comment]
Ha!

**Comment by ZachYoshikawa** [comment]
Humans are now People. ^_^

**Comment by AmberSJones** [comment]
Excellent.
