### ISSUE TITLE
Reorganize Menus

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#141]
As alluded to in #139 , we need to discuss some reorganization of the homepage and menus. We need prominant links to the creation of SiteVisits, Calibrations, Deployments, and Other Actions. They're a bit buried at this point.

**Comment by ZachYoshikawa** [comment]
This sounds like we should briefly meet to map this out. I will be around next week.

**Comment by AmberSJones** [comment]
Add a home tab, put the quick links on the home page. Quick links should include:
-Create Site Visit
-Create Calibration
-Create Deployment
-Create Other Action
-Add Equipment

**Comment by AmberSJones** [comment]
The homepage looks great! A few edits:
- [ ] I think we should remove the title (ODM2 Sensor) so that 'Equipment Management' is the title. But then change it to 'ODM2 Equipment Management'
- [ ] In the text, change the second sentence to 'It is based on the Equipment Extension of the Observations Data Model 2 (ODM2).' Keep the link.
- [ ] There are some resizing issues (see below screenshot). Can we keep the iUTAH and NSF logos on the same line and better position the 'Create a new...' box when the window is smaller?

![image](https://cloud.githubusercontent.com/assets/5023186/11628884/feddcbf4-9cb1-11e5-9f52-8b3f906bec0c.png)

**Comment by ZachYoshikawa** [comment]
I will make those changes tonight. I designed the logos and quick links box to move that way so it is always visible when the page is shrunk. But I agree with you now that having them fixed will be better.

**Comment by AmberSJones** [comment]
Thanks. I think it's important to keep the 'Create New' box front and center even with re-sizing- I don't know if the text could be resized instead of the 'Create New' box?

**Comment by ZachYoshikawa** [comment]
As discussed, should be good to go now.

**Comment by AmberSJones** [comment]
Maybe I wasn't totally clear in our conversation- can we have the text resized as the screen is made smaller so that the 'Create New' box remains in the window without having to scroll? If that's not possible, maybe the best solution is to move the 'Create New' box to the left of the text.

**Comment by AmberSJones** [comment]
Really minor, but we need a period after the link in the Description paragraph.
![image](https://cloud.githubusercontent.com/assets/5023186/12592217/bd6c6038-c428-11e5-9d48-ab992b840e79.png)

**Comment by ZachYoshikawa** [comment]
Nice catch! Fixed.

**Comment by AmberSJones** [comment]
Thanks! Closing.
