### ISSUE TITLE
ODM2Sensor not compatible with postgresql

### ISSUE THREAD

**Issue by miguelcleon** [UCHIC/ODM2Sensor#142]
In order to get parts of ODM2Sensor to work with a postgresql ODM2 database I had to make a few changes. For the model sites: 

db_table = 'ODM2].[Sites'
needed to be changed to: 
db_table = 'sites' 

I also needed to change all of the column names to lowercase. 

I'm not sure how this should be managed but as is ODM2Sensor won't work with ODM2 in postgresql.

**Comment by jcaraballo17** [comment]
has been fixed for over a year. 
closing.
