### ISSUE TITLE
Implement Deletion of an Action

### ISSUE THREAD

**Issue by ghost** [UCHIC/ODM2Sensor#143]
Currently there are no defined functions to delete an Action object, meaning nothing can be deleted in the 'Action' tab.

The following needs to be happen (and then probably more that I haven't thought of)

In edit_views.py: creation of def delete_action() next to edit_action()
In edit_urls.py: create url links
Somehow make the function work for all action types

@jcaraballo17 Unlike creating a site, person, organization, and most of the objects, creating actions are mashed together in one class. It looks like an attempt of inheritance, but it is just a big mess that is hard to manipulate for the actions. What do you think we should do about it?

**Comment by ZachYoshikawa** [comment]
@AmberSJones Was it intentionally designed to not delete actions?

**Comment by AmberSJones** [comment]
Hmmm. I think we should be able to delete an action, but as it is so complex, we need to implement a warning to make sure that users actually want to delete...

**Comment by Elijahwalkerwest** [comment]
Implemented and pushed to sandbox.
