### ISSUE TITLE
Button Not Working on Site Visit Summary Page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#144]
After the creation of a Site Visit, the summary page is displayed. The 'Edit this Site Visit' button just goes to the creation of a new site visit- not the editing of that site visit.

![image](https://cloud.githubusercontent.com/assets/5023186/12593320/b73accfe-c42d-11e5-9740-19fb3b759d17.png)

**Comment by AmberSJones** [comment]
I continue having issues with this. The 'Edit this Site Visit' button works and allows me to save, but I often get a '500 Server Error'. I think that it may occur when I try to add another Action when editing the Site Visit.

Additional strange behavior: I create a Site Visit with some Actions. I hit the button to Edit that Site Visit. I perform some edits. I hit 'Update'. I get errors- the Equipment that was previously entered for each action is no longer selected.

![image](https://cloud.githubusercontent.com/assets/5023186/12800946/ec2f5bfa-ca95-11e5-9d88-f6ec468d8aab.png)

**Comment by jcaraballo17** [comment]
Moved this to issue #152 for organization purposes.
