### ISSUE TITLE
Action Type selection should filter Methods

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#145]
MethodType and ActionType are identical. When an ActionType is selected, the Methods list should be filtered to only display Methods of that ActionType/MethodType.

**Comment by jcaraballo17** [comment]
There's not a method for each methodtype in the database, so when you select an action type in the action form, sometimes the Method field has no values to select and it is a required field. What should I do in that case?

**Comment by AmberSJones** [comment]
We need some sort of message to come up to say that there are no Methods of that type and prompt to select another Action Type.

**Comment by AmberSJones** [comment]
Closing this issue. The outstanding work of adding a message and adding Methods will be added as a separate issue.
