### ISSUE TITLE
Ability to create methods

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#147]
We need to add the ability to create methods.

**Comment by AmberSJones** [comment]
I am vacillating on whether or not we should implement this. Wait on it for now.

**Comment by ZachYoshikawa** [comment]
@AmberSJones We already implemented the creation of Methods. The button can be accessed through Actions -> Methods.

**Comment by ZachYoshikawa** [comment]
@AmberSJones The functionality to create and delete Method Types already exists. It's as easy as placing buttons on the table to do so.

**Comment by AmberSJones** [comment]
Ok. Let's add the buttons, then!
