### ISSUE TITLE
No Methods for selected ActionType

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#148]
We need a of message to appear if there are no Methods for a selected ActionType and prompt to select a different Action Type. I think the text should say "No Methods exist for that Action Type. Select a different ActionType or create a new Method."

**Comment by AmberSJones** [comment]
This is great. Can we move the Method field so that it is immediately below ActionType?

**Comment by ZachYoshikawa** [comment]
It is done.
