### ISSUE TITLE
Restrict Equipment Used for each Deployment Action to be 1:1

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#151]
In order for retrievals to function correctly, we need to constrain the equipment used for a deployment. Instead of a deployment using multiple pieces of equipment, a deployment should only use one piece of equipment. So, deployments of multiple equipment require multiple deployment actions. 

This could either be done by 1. only permitting the selection of a single piece of equipment on the deployment form, or 2. permitting multiple pieces of equipment to be selected, but creating separate deployment actions for each piece of equipment selected.

**Comment by ZachYoshikawa** [comment]
I am going with choice 1. :)

**Comment by ZachYoshikawa** [comment]
I'm fixing it right now.

**Comment by AmberSJones** [comment]
Ok- I think this is addressed. Closing.
