### ISSUE TITLE
Retrieval Refinements: Filtering only active deployments

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#154]
If I initiate a Retrieval by clicking on the ‘Retrieve’ button, then the ‘Deployment’ should be selected on the ‘Create Retrieval Action’ form but it doesn't always happen. This may be because the deployment already has an end date- so the 'Retrieve' button should be hidden from deployment detail if it's not current.

**Comment by jcaraballo17** [comment]
This problem was part of issue #155, closing.
