### ISSUE TITLE
Retrieval Refinements: Filtering the deployments by the selected method and vice versa

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#156]
The ActionType of Equipment or Instrument Retrieval should be automatically selected based on the deployment selected- whether it was an Equipment or Instrument Deployment. This should also occur in reverse- if Equipment or Instrument Retrieval is selected, the possible deployments should filter based on the type of deployment. I think there may be some filtering implemented, but it seems like it might be currently in reverse?

**Comment by jcaraballo17** [comment]
> The ActionType of Equipment or Instrument Retrieval should be automatically selected based on the deployment selected- whether it was an Equipment or Instrument Deployment.

It currently works that way, but not the other way around. Working on it!

**Comment by AmberSJones** [comment]
I can't test this. I think there is some filtering occurring on the Deployments even without a Method selected- it seems that none of the Equipment that was deployed as MethodType Equipment Deployment is being shown.

Also, it does not permit me to select the method first so that I can use the Method to filter Deployments.

**Comment by AmberSJones** [comment]
Interestingly, this is functional when implementing a Retrieval on the Site Visit form, but not on the Retrieval form.

**Comment by AmberSJones** [comment]
I think this is all addressed. Closing.
