### ISSUE TITLE
New Site Visit Form: Changing Action Type needs to change the other fields

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#157]
When an Action Type is selected on the Create Site Visit form, the other fields change depending on the Action Type selected. However, there are some cases where the fields don't necessarily update. I've noticed this particularly when going from a retrieval to a deployment- the Equipment Used field is no longer there: 

![image](https://cloud.githubusercontent.com/assets/5023186/13435630/6eb885da-df98-11e5-967f-acfd4129d023.png)

**Comment by jcaraballo17** [comment]
Solved this issue unintentionally in commit f29da495b08f79875897b2dc47a50916b3105bf4.

**Comment by AmberSJones** [comment]
Great, closing.
