### ISSUE TITLE
Extra field when creating new annotation

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#162]
When trying to create a new annotation, there is an 'Annotation' selection box. This should only be there for selecting an existing annotation:
![image](https://cloud.githubusercontent.com/assets/5023186/13612860/d9b9702c-e526-11e5-802c-049242e00dc1.png)

**Comment by jcaraballo17** [comment]
What if you select 'New Annotation' and the field disappears and then you change your mind and want to select an existing annotation?

**Comment by AmberSJones** [comment]
Then you can just hit the 'Remove Annotation' button and then hit the 'Add Annotation' button. Not too difficult.

**Comment by jcaraballo17** [comment]
Alright.
