### ISSUE TITLE
Creating a Site Visit Failing

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#163]
I just tried to create a site visit that included several child actions and several annotations. The site visit is not being created, and I am not getting an error- the screen just flashes. I have tried stripping it down to determine which action or annotation might be causing the issue- it seems that including ANY child action will not create the site visit.

**Comment by AmberSJones** [comment]
Later I revisited the details of this site visit, and it seems like at least some of the child actions were added.

**Comment by AmberSJones** [comment]
This is still occurring for me. One thing that is interesting, if I have a calibration, it clears the Equipment that I had selected and tells me that an equipment needs to be provided. If I don't have a calibration, it still flashes and stays on the Site Visit form.
![image](https://cloud.githubusercontent.com/assets/5023186/13812379/6afcabce-eb41-11e5-9c08-d6fd99c2e292.png)

**Comment by ZachYoshikawa** [comment]
The site visit will update properly now. However, if a required field is removed, it will do the flashy thing and weirdly change from "Update Site Visit" to "Create Site Visit". The results action also needs to be validated in our code (super easy). @jcaraballo17 Since you are updating the results, could you look at the actions-form.html template? Maybe you can see why it is redirecting in a strange way.

**Comment by AmberSJones** [comment]
I'm still experiencing this issue. 

Sometimes I am getting the flash and the change from "Update Site Visit" to "Create Site Visit" that @ZachYoshikawa mentioned. (All required fields are present, however.) 

Other times when I add an action to an existing site visit, it takes me to the Site Visit Summary and it has failed to add the action to that Site Visit.

**Comment by AmberSJones** [comment]
I am always unsuccessful in trying to create a SiteVisit with a few nested actions from scratch. In particular, if there is any equipment selected for an action, it gets reset and the form tells me that the field is required. Note that this was all complete and correct before clicking "create"! I have also had a few cases of server error (which I think is probably related to creating actions that don't involve equipment).

![image](https://cloud.githubusercontent.com/assets/5023186/14086090/9d643eee-f4e0-11e5-81ea-b32eb94ed80c.png)
![image](https://cloud.githubusercontent.com/assets/5023186/14086102/a794c488-f4e0-11e5-8974-567ae109f775.png)

**Comment by jcaraballo17** [comment]
@AmberSJones, is it possible to come up with a way of replicating the original error where the actions are not added to the site visit? I've tried everything on my local machine and the sandbox server and cannot make it happen.

**Comment by jcaraballo17** [comment]
The bug which redirected to the site visit form after clicking on Create or Update was caused by the Equipment and Method fields' validation. Also, when editing a site visit, the actions in the form were always created as new actions, and the ones already linked to the site visit were not being updated. Those new actions did not get linked through the RelatedAction table, so the site visit kept the old actions, and the detail of each new action was only reachable by manually writing their action id into the url.

**Comment by AmberSJones** [comment]
I'm still experiencing this issue. I tried to create a new site visit. I included several actions:
1. equipment deployment 
2. instrument deployment (with three results)
3. field activity (using no equipment)
4. instrument calibration (using an equipment)

After I hit "Create", the page flashed and it brought me back to the form telling me "This field is required" for the Equipment Used on the Calibration. However, I had selected an equipment before hitting "Create". There were several things in the form that changed after I hit "Create": 

1. For the instrument deployment, a different instrument than what I had previously selected is displayed. The Results that I had entered are no longer shown:
![image](https://cloud.githubusercontent.com/assets/5023186/15873588/9f5aad0a-2cbc-11e6-8954-c087ccd12997.png)

2. For the instrument calibration, I had selected an equipment. It is no longer selected here:
![image](https://cloud.githubusercontent.com/assets/5023186/15873615/b61723ac-2cbc-11e6-989b-8bcfb23b818d.png)

3. For the instrument calibration, a different Instrument Output Variable is shown from the one I had selected:
![image](https://cloud.githubusercontent.com/assets/5023186/15873639/d00d6276-2cbc-11e6-84c7-80cb31e4435f.png)

**Comment by AmberSJones** [comment]
I just created a site visit with only a retrieval action and it was successful.

**Comment by AmberSJones** [comment]
Also successful: site visit with only an equipment deployment action, site visit with only an instrument deployment action, site visit with only an instrument calibration action. 

Then I tried the combination of the three actions as part of the same site visit and got the server error. 
![image](https://cloud.githubusercontent.com/assets/5023186/15875026/53c24b08-2cc3-11e6-81a3-c36fac890279.png)

**Comment by jcaraballo17** [comment]
If there's still an issue creating a site visit it's probably not related to any of this (there are already several different issues here treated as one).
Can we create a new issue if some error comes up in the testing?

**Comment by AmberSJones** [comment]
@jcaraballo17 I am happy to create new issues if needed. And WHOA I actually had a new site visit with multiple nested actions CREATE! So, I'll close this issue given some success. However, I have experienced some failures, and will create new issues accordingly.

![image](https://cloud.githubusercontent.com/assets/5023186/19576040/c11130f0-96ce-11e6-8160-65ff37b6e54b.png)
