### ISSUE TITLE
Weirdness is the Site Visit Summary page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#164]
The parsing of the details in the Site Visit Summary page is strange. Some elements are not on new lines, the crew is split up, and the Annotations are repeated.

![image](https://cloud.githubusercontent.com/assets/5023186/13613684/67138928-e52a-11e5-8ed7-dfc9cca663d3.png)

**Comment by AmberSJones** [comment]
The repeated Annotations is addressed. The DateTimes are still strange, but I think that could be addressed by shifting the divider between the 'Site Visit Details' column and the elements to the left.

**Comment by ZachYoshikawa** [comment]
This is what I see on my screen. It is readable for me. What is it about the column you don't like?

 
![sitevisitdetails](https://cloud.githubusercontent.com/assets/14823701/14033735/4c814482-f1e2-11e5-823d-4212a9899245.PNG)

**Comment by AmberSJones** [comment]
I suggest making the left column narrower so that there is more room for the information in the right column. The text in the left column can wrap if needed, but there should be plenty of room for it as that text is typically very short.
