### ISSUE TITLE
'Edit Deployment Description' undoes a retrieval

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#168]
If an equipment has been retrieved and then its deployment is edited (i.e., 'Edit Deployment Description') on the Deployment Details page), then the retrieval is undone/removed.

**Comment by AmberSJones** [comment]
This is still occurring for me.

**Comment by ZachYoshikawa** [comment]
@AmberSJones The Site Visit Details page now links to the correct Deployment Details page. I created Methods for Equipment and Instrument Deployments as well as Retrievals on the Sandbox Server. This should enable full testing of the retrieval functionality. I hope it works for you now! Thanks for being patient. :)

**Comment by AmberSJones** [comment]
I can't test the original issue here. @ZachYoshikawa , as I'm getting a new error. See the below workflow. I'm not sure about what you are referring to in your previous comment as I'm not using the Site Visit Details page for this issue. Here's what's happening for me:

1. Go to Deployment Details page:
![image](https://cloud.githubusercontent.com/assets/5023186/14084297/51a21962-f4d7-11e5-84df-a89cf656f071.png)
2. Click 'Edit Deployment Description':
![image](https://cloud.githubusercontent.com/assets/5023186/14084218/f67f0e64-f4d6-11e5-8ddb-b45938f5d185.png)
3. I edit the Deployment and click 'Update Deployment Action' and I get this screen:
![image](https://cloud.githubusercontent.com/assets/5023186/14084246/172e07fa-f4d7-11e5-8a80-ef1ae313346c.png)

**Comment by ZachYoshikawa** [comment]
That workflow works on my development server, but not on sandbox. I'm sorry I didn't catch this sooner. I think sandbox has issues with its static files, even though we have been updating them. I'll look into it.

**Comment by jcaraballo17** [comment]
Editing a deployment action changed, and in some cases deleted, it's end datetime value. This made the deployment be shown as if they were currently deployed, and created some inconsistencies between the deployment and retrieval times.

**Comment by AmberSJones** [comment]
There is still weirdness occurring related to retrievals being un-done.

I created a deployment and then created a retrieval of that equipment. Here is the record in the deployments table:
![image](https://cloud.githubusercontent.com/assets/5023186/15874180/37ea3138-2cbf-11e6-9aa7-5383a53ccda2.png)

When I go to the deployment details page, the deployment end date is missing:
![image](https://cloud.githubusercontent.com/assets/5023186/15874203/50c2b4e6-2cbf-11e6-97c1-d49975847ef7.png)

When I edit the deployment details, it now keeps the end date (does not undo the retrieval as before). So, I think the functionality of this issue is fixed, but the display on the deployment details page is incorrect.
![image](https://cloud.githubusercontent.com/assets/5023186/15874331/e02ebf3a-2cbf-11e6-8acc-bf6ad06d4c85.png)

**Comment by AmberSJones** [comment]
I am trying to edit the same deployment referenced in the above screenshot. The issue now is that the equipment used is not selected on the Update Deployment Action page. I expect to see the 61012011 Rotronic Sensor here.
![image](https://cloud.githubusercontent.com/assets/5023186/19574518/01f501e8-96c8-11e6-8317-4d07a2174dcb.png)

**Comment by Elijahwalkerwest** [comment]
The issue of it moving to the create page comes from the selected equipment not existing in the database. Should be fixed, because I have also fixed the issue of it not auto populating correctly. It should now properly pull the right equipment from details in to equipment used. 

Ready for testing, django-elijah branch

**Comment by AmberSJones** [comment]
How do I test on different branches for this project? I've only ever tested on the sandbox server.

**Comment by Elijahwalkerwest** [comment]
Sorry, I'll get that branch merged and ready for testing on the deployment server tomorrow.

**Comment by AmberSJones** [comment]
No problem.

**Comment by AmberSJones** [comment]
This seems to be addressed.
