### ISSUE TITLE
Case where equipment not being filtered on calibration action form

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#185]
From a site visit details page, I clicked on 'Add calibration'. It brought me to the Create Calibration page. The equipment is not being filtered for that site. Equipment filtering is also not occurring for the Create Generic Action page.

![image](https://cloud.githubusercontent.com/assets/5023186/13618143/b0130d78-e53f-11e5-85ee-69ad56a6155e.png)

**Comment by jcaraballo17** [comment]
I don't see this happening even on the sandbox server and with the same site visit. A web service is called to get the equipment used in a site when you select a site visit, maybe it took a little bit more than usual to load?

**Comment by AmberSJones** [comment]
I'm still experiencing it. Let's take a look at it together.
