### ISSUE TITLE
Results Block changes margins/alignment

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#193]
Whenever an action of type instrument deployment is selected for addition on the New Site Visit form, a block is created for the addition of Results. This is good. What is not good is that it changes/shifts/narrows the alignment of all elements of the entry form.

Before:
![image](https://cloud.githubusercontent.com/assets/5023186/14085489/6185d976-f4dd-11e5-8e22-907e3c9af849.png)

After:
![image](https://cloud.githubusercontent.com/assets/5023186/14085477/4edf5b08-f4dd-11e5-9883-8354461978e1.png)

**Comment by jcaraballo17** [comment]
Fixed after fixing an error in the javascript code.
