### ISSUE TITLE
Equipment not being filtered

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#194]
@jcaraballo17 - I know that you have implemented this and fixed it and probably fixed it again. So, for no obvious reason, equipment is no longer being filtered by site and datetime. This should be occuring for all actions except for deployments. Have we reverted to some older code?!

![image](https://cloud.githubusercontent.com/assets/5023186/14085548/b72f3a84-f4dd-11e5-987d-935009b85dc2.png)

**Comment by jcaraballo17** [comment]
Fixed equipment filtering.
