### ISSUE TITLE
Spacing on Details pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#195]
There is some funky spacing/alignment on some of the Details pages- the left-most columns are disproportionately wide and the right columns are too narrow. This is new- I thought the margins seemed good previously. Also, when equipment is shown, the "Show Instrument Measured Variables" and "Show Related Equipment" buttons are strangely narrow.

![image](https://cloud.githubusercontent.com/assets/5023186/14083440/ff980f18-f4d2-11e5-96a5-291c1b291692.png)
![image](https://cloud.githubusercontent.com/assets/5023186/14084006/f253210a-f4d5-11e5-820a-0067de9990ed.png)
![image](https://cloud.githubusercontent.com/assets/5023186/14085661/56cce492-f4de-11e5-9c56-c24eb0b3847f.png)

**Comment by jcaraballo17** [comment]
Looks fixed.
