### ISSUE TITLE
Filter Equipment to only show Sensors for "Instrument" Actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#199]
When an action that is an "Instrument" action is selected (Instrument calibration, Instrument deployment, Instrument retrieval), the possible "Equipment Used" should be filtered to only show sensors. Otherwise, a battery or solar panel could be erroneously deployed as a sensor/instrument.

**Comment by horsburgh** [comment]
I like this idea.  And we should consider it for additional implementations.  But, it complicates things.  I think we have to trust that users have some level of understanding of what they are doing.  In any case, I wouldn't consider this a bug.  I'm going to change the label to enhancement.

**Comment by Elijahwalkerwest** [comment]
Implemented and ready for testing. Works for both equipment and instruments.

**Comment by AmberSJones** [comment]
I'm not observing this functioning. Has it been pushed to the sandbox server?

**Comment by Elijahwalkerwest** [comment]
The battery and solar panel that are showing up when filtering by instrument are in fact, in the database ,marked with equipmentmodelid 3, that equipmentmodelid is in fact marked as IsInstrument = true in the database.

That is equipment ID 1769, and 667

**Comment by Elijahwalkerwest** [comment]
In addition, I want to double check. This specific filtering should only be for deployments, right? Calibration and maintenance filter by what is deployed at the site, they should not be filtering this way, right? Or do you want an additional layer of filtering that filter by site AND by isInstrument

**Comment by AmberSJones** [comment]
I can take a look at those particular pieces of equipment that may be incorrectly identified by "IsInstrument".

In the cases of calibrations, maintenance, etc., the desired functionality is to have the equipment filtered by site as well as by equipment type (see the original issue), so yes, two layers of filtering.

**Comment by Elijahwalkerwest** [comment]
Have the second level filtering working. Will push tomorrow after I get the delete action functioning so you can test both.

**Comment by AmberSJones** [comment]
This is looking good. Closing.
