### ISSUE TITLE
Server Issue when trying to create retrieval

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#201]
I am getting server error when trying to create a retrieval. I _think_ this is only occurring with the 'Retrieve' button on the Deployment Details page because I have had success in creating retrievals in other ways.

![image](https://cloud.githubusercontent.com/assets/5023186/19574271/c42ad938-96c6-11e6-89de-c93c54aaed86.png)

**Comment by AmberSJones** [comment]
Yep, it's still occurring.

Go to "Deployments" and select a deployment action. Click on the "Retrieve" button and complete the required fields. I get server error. Here is the deployment that I am trying to retrieve: http://django.uwrl.usu.edu/equipment/actions/deployment-detail/1074/

**Comment by Elijahwalkerwest** [comment]
Got it. Will mark for testing when deployed to sandbox with other fixes.

**Comment by Elijahwalkerwest** [comment]
Ready for testing.

**Comment by AmberSJones** [comment]
So, now when I try to retrieve, I don't get the error, but the desired behavior is not achieved. I complete the required fields and hit the "Create Retrieval Action" button. The screen flashes and brings me to the generic "Create Retrieval Action" page - so the deployment of interest is now not selected.

**Comment by Elijahwalkerwest** [comment]
AGh! Ok I will work on that, thank you!

**Comment by Elijahwalkerwest** [comment]
Hmmm that wasn't happening on my local env. I will get it figured out.

**Comment by Elijahwalkerwest** [comment]
Fixed with latest deployment.

**Comment by AmberSJones** [comment]
I think we may have actually regressed with this one. I'm now getting the error again!

**Comment by Elijahwalkerwest** [comment]
Not happening locally, very strange. Looking in to it today.

**Comment by Elijahwalkerwest** [comment]
Fix deployed and ready for testing.

**Comment by AmberSJones** [comment]
I haven't seen this work, but I think it should when the database gets fixed for retrievals, so closing.
