### ISSUE TITLE
Unable to Create Site Visit with multiple nested child actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#202]
When I try to create a Site Visit with multiple nested child actions, I get server error. This is only sometimes... as noted, I have had some success. I'll try to identify a pattern.

![image](https://cloud.githubusercontent.com/assets/5023186/19575659/ff6b2f88-96cc-11e6-95b2-e6065eb83484.png)

**Comment by Elijahwalkerwest** [comment]
Haven't been able to replicate it myself. If you replicate it please note how you did so.

**Comment by AmberSJones** [comment]
I haven't been able to reproduce this exact issue in this round of testing. Closing for now.
