### ISSUE TITLE
Discrepancy in Equipment when trying to edit Site Visit

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#203]
I created this site visit with an equipment deployment.
![image](https://cloud.githubusercontent.com/assets/5023186/19575694/3247adbe-96cd-11e6-82ff-7a48f8bde075.png)

Now I try to edit this site visit. The equipment used is different:
![image](https://cloud.githubusercontent.com/assets/5023186/19575702/3bf61350-96cd-11e6-80a4-d7bda1268425.png)

**Comment by Elijahwalkerwest** [comment]
Should be fixed along with #168 fix. Will notify when deployed and ready for testing.

**Comment by Elijahwalkerwest** [comment]
Ready for testing.

**Comment by AmberSJones** [comment]
This appears to be addressed.
