### ISSUE TITLE
Issues creating site visits

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#210]
I have been testing creating site visits with multiple nested action and am experiencing issues. I'm not sure if these are related or not. They are similar to issues that we've had in the past that have been addressed/closed. Below are the steps I've followed that have resulted in errors:

1. I successfully create a site visit with a few actions. Below is the summary page. When I click "Edit" from the summary page, I get the 2nd screenshot- for the retrieval actions, the associated deployment is not selected. Another problem- one of the actions was a calibration and now it is shown as a retrieval.
![image](https://cloud.githubusercontent.com/assets/5023186/25044945/dd95e85e-20e6-11e7-90a3-f40d7d7df789.png)
![image](https://cloud.githubusercontent.com/assets/5023186/25044964/fb2de844-20e6-11e7-8258-a7ce639a4c04.png)

2. I successfully create a site visit with a few actions. From the Actions details page, I click "Edit". I get an error. 
![image](https://cloud.githubusercontent.com/assets/5023186/25045108/abb8569a-20e7-11e7-83a0-a82926819715.png)
![image](https://cloud.githubusercontent.com/assets/5023186/25045115/b64371c6-20e7-11e7-8469-00ee05e8fb21.png)

3. I successfully create a site visit with a few actions. From the summary page, I click "Edit". Everything looks good. I modify an action description and click "Update". I get an error. If I try to edit again, only a few of the Actions show up.
![image](https://cloud.githubusercontent.com/assets/5023186/25045170/05664c38-20e8-11e7-8619-0c9a722278dc.png)
![image](https://cloud.githubusercontent.com/assets/5023186/25045183/1d4476f4-20e8-11e7-95b2-d8ca4f5d0338.png)
![image](https://cloud.githubusercontent.com/assets/5023186/25045198/348a4bf4-20e8-11e7-9c1c-59f37f751ec7.png)

**Comment by Elijahwalkerwest** [comment]
Fix deployed an ready for testing.

**Comment by AmberSJones** [comment]
Number 1 and number 2 seemed fine, but when I went to look at the site visit details page, many of the actions were not there:
![image](https://cloud.githubusercontent.com/assets/5023186/25461091/37dab710-2aa4-11e7-9f8f-39829c107f86.png)

**Comment by AmberSJones** [comment]
When I try to edit a site visit, in some cases I am able to:
![image](https://cloud.githubusercontent.com/assets/5023186/25461160/9a9def48-2aa4-11e7-8b7e-0d812775c9de.png)
but then I get this error:
![image](https://cloud.githubusercontent.com/assets/5023186/25461207/da037a0e-2aa4-11e7-86d0-632c8479c804.png)

In other cases, I get this error without even letting me go to the edit screen:
![image](https://cloud.githubusercontent.com/assets/5023186/25461169/a4ba1df8-2aa4-11e7-96bb-7a406d4f0050.png)

**Comment by AmberSJones** [comment]
@Elijahwalkerwest have the remaining issues in this thread been addressed?

**Comment by Elijahwalkerwest** [comment]
They should be yes. These issues were an artifact of the bad data. This is ready for testing.

**Comment by Elijahwalkerwest** [comment]
Tested on sandbox. It appears I was correct, and this was an artifact of the corrupted data Juan and I fixed. This is now resolved. Closing.
