### ISSUE TITLE
Person redirects incorrectly

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#233]
I try to edit a person. When I complete the editing by either saving or clicking “cancel”, it brings up the details page for a completely DIFFERENT person. The edits that I made to the original person record are retained correctly.

**Comment by Elijahwalkerwest** [comment]
Working on this one now. Need to re-structure the person views to work with person_id's instead of affiliation_id's

**Comment by Elijahwalkerwest** [comment]
Fixed and deployed. 

Side note, this also fixed deleting people.
