### ISSUE TITLE
Issues when deleting actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#238]
I add a calibration action to an existing site visit. Seems fine. I then click “Edit Calibration Description”. I make an edit and click save. I get an error (1st image). Similar behavior if I delete an action of type deployment (2nd image). In both cases, deletion does actually occur.

![image](https://user-images.githubusercontent.com/5023186/34801124-26838374-f624-11e7-8c71-1b1cf456eca3.png)

![image](https://user-images.githubusercontent.com/5023186/34801141-38c235c6-f624-11e7-8606-37e0adc5c3e1.png)

**Comment by Elijahwalkerwest** [comment]
Fixed, just need to merge and deploy.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing.

**Comment by AmberSJones** [comment]
Experiencing the exact same behavior.

**Comment by Elijahwalkerwest** [comment]
This should be fixed after sandbox fixes. Testing it on sandbox now and it seems to be working. Closing.
