### ISSUE TITLE
Errors editing site visit

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#239]
I was making some edits to a site visit. Got this result. Note that this site visit does actually exist.

![image](https://user-images.githubusercontent.com/5023186/34801213-b214bf8e-f624-11e7-822a-d10b45e4b077.png)

**Comment by Elijahwalkerwest** [comment]
I made some changes to the edit site visit. I'm not sure what steps or edits were done to cause this, but I haven't run in to any issues editing site visits since my fixes. Try testing again and letting me know!

**Comment by AmberSJones** [comment]
Still getting an error for this. Try just entering this url.
http://django.uwrl.usu.edu/equipment/actions/edit-site-visit/97/
Site visit does exist:
http://django.uwrl.usu.edu/equipment/actions/visit-detail/97/

**Comment by Elijahwalkerwest** [comment]
Same issue as #237

**Comment by Elijahwalkerwest** [comment]
Closing this as issue is being tracked in #237
