### ISSUE TITLE
Unable to add Results when creating a Deployment Action

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#240]
I’m trying to create a Deployment Action (not as a nested action). It does not permit me to add results. The button is there, but it doesn’t bring up any fields to complete.

![image](https://user-images.githubusercontent.com/5023186/34801305-2e2c3aca-f625-11e7-94ee-fee8b81be921.png)

**Comment by Elijahwalkerwest** [comment]
Fixed and deployed to sandbox.

**Comment by AmberSJones** [comment]
This specific issue is addressed (though another is identified... will start new issue). Closing.
