### ISSUE TITLE
Issues with Results

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#244]
I created a site visit with an instrument deployment with some results. When I later edit the site visit, the displayed results are different than the ones that I created. 
Here's what is should be:
![image](https://user-images.githubusercontent.com/5023186/34828059-7ec15014-f699-11e7-9beb-b793b29c09de.png)
Here's what appears when I edit:
![image](https://user-images.githubusercontent.com/5023186/34827885-dc153ff6-f698-11e7-9244-453ced5cffbb.png)

**Comment by Elijahwalkerwest** [comment]
Working on this one now.

**Comment by Elijahwalkerwest** [comment]
Should be resolved and ready for testing.

**Comment by AmberSJones** [comment]
Now when I try to update the Deployment Action, I cannot see the Results at all.
Here is the details page:
http://django.uwrl.usu.edu/equipment/actions/deployment-detail/948/
![image](https://user-images.githubusercontent.com/5023186/36758159-cedf9770-1bd0-11e8-85ce-3ba54cc0c13a.png)

Here is the edit page:
http://django.uwrl.usu.edu/equipment/actions/create-action/EquipmentDeployment/948/
![image](https://user-images.githubusercontent.com/5023186/36758140-be176aee-1bd0-11e8-9718-66e3b4c73758.png)

**Comment by AmberSJones** [comment]
Similar to the very original issue, for a site visit, the Results are correct, but then when editing the Site Visit, the equipment is not populated and the Instrument Output Variables are incorrectly populated. The Units, Processing Level, and Sampled Medium are correct.
http://django.uwrl.usu.edu/equipment/actions/create-site-visit/summary/1039/
![image](https://user-images.githubusercontent.com/5023186/36759029-52dd2f68-1bd3-11e8-9906-4c76bf97e082.png)
http://django.uwrl.usu.edu/equipment/actions/edit-site-visit/1039/
![image](https://user-images.githubusercontent.com/5023186/36759056-68750076-1bd3-11e8-8876-dafaddfac3dd.png)

**Comment by Elijahwalkerwest** [comment]
Fixed, but not pushed yet. Whoever designed the edit site visit didn't understand the database. And instrument output variable id != variable id Will push tomorrow.

**Comment by AmberSJones** [comment]
This appears to be functional - except for this issues. When editing the site visit, I can successfully view and edit the Results - and the correct Results are listed. However, there is an erroneous warning.
![image](https://user-images.githubusercontent.com/5023186/37054883-6845461e-213d-11e8-9d88-107158e571ea.png)

**Comment by Elijahwalkerwest** [comment]
Resolved and pushed.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing!

**Comment by AmberSJones** [comment]
Ok, I think this is addressed.

**Comment by AmberSJones** [comment]
Ok - i think this is addressed.
