### ISSUE TITLE
Issue with Retrieval Nested Action

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#245]
I create a site visit with 2 nested actions: a deployment and a retrieval. The I then click "Edit Site Visit". I get an error. When I go back to the Site Visit page, the retrieval is gone. When I dig deeper and investigate that retrieval, it is saved. But it does not appear as expected as associated with the site visit.

**Comment by Elijahwalkerwest** [comment]
Should be fixed, please test!

**Comment by AmberSJones** [comment]
I cannot test this yet because I cannot currently create the Site Visit with these types of nested actions.

**Comment by AmberSJones** [comment]
Looks to be addressed.
