### ISSUE TITLE
Unable to create site visit with nested actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#247]
I attempt to create a site visit with a deployment action, two field activity actions, and three retrieval actions. When I click "Create", the site returns to the create site visit form. The site visit is not created. When I remove some of the retrievals from the action, the site visit creation can occur. Then it permits me to add the retrievals.

**Comment by Elijahwalkerwest** [comment]
Narrowing this down some. This behavior seems linked to Instrument Revrieval rather than nested actions. Any time your action is instrument retrieval it breaks.

**Comment by Elijahwalkerwest** [comment]
Should be ready for testing.

**Comment by AmberSJones** [comment]
I am still experiencing this issue - with consistency. Here is an example with multiple screen shots. Note that the equipment that I selected for deployment and the associated results came back blank from what I had populated.

![image](https://user-images.githubusercontent.com/5023186/36758619-3a8b8e06-1bd2-11e8-9bfe-c7089f287ee7.png)
![image](https://user-images.githubusercontent.com/5023186/36758637-45a07e96-1bd2-11e8-8cda-08ea6a41985d.png)
![image](https://user-images.githubusercontent.com/5023186/36758650-4f892be2-1bd2-11e8-98d7-99f5d976f879.png)

**Comment by AmberSJones** [comment]
Ok- the site visit creates successfully! But then, I cannot edit it at all.
http://django.uwrl.usu.edu/equipment/actions/edit-site-visit/1066/
![image](https://user-images.githubusercontent.com/5023186/37056738-82c8943c-2142-11e8-9834-661e77edbb7e.png)

**Comment by Elijahwalkerwest** [comment]
This should actually be resolved as of my changes today. Merging and deploying now

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing.

**Comment by AmberSJones** [comment]
Functional. Hooray!
