### ISSUE TITLE
edit_site_visit creating ghost results when a required field isn't present when updating

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#252]
If you either create a site visit or edit one and have an instrument deployment, and fail to fill out required fields, it will add a ghost result that you can't delete, which will then break the update.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing!

**Comment by AmberSJones** [comment]
I'm not sure if this is directly related, but in trying to test this issue, I'm experiencing errors creating/editing site visits. These cases included instrument deployment actions with some results as well as an equipment deployment and a few other actions.

![image](https://user-images.githubusercontent.com/5023186/38043258-db031982-3273-11e8-80b9-2c3a88d26917.png)

![image](https://user-images.githubusercontent.com/5023186/38043243-cd7d7c8a-3273-11e8-8194-2f9d48049ae5.png)

**Comment by AmberSJones** [comment]
I think the above issue is something different. This appears to be addressed.
