### ISSUE TITLE
Update Deployment Action does not include relevant details

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#257]
Here's a deployment I created. When I try to edit it, the equipment is not selected nor are the results included.
http://django.uwrl.usu.edu/equipment/actions/deployment-detail/1051/
![image](https://user-images.githubusercontent.com/5023186/36759345-44b2d798-1bd4-11e8-8553-ced0bf09a691.png)

http://django.uwrl.usu.edu/equipment/actions/create-action/EquipmentDeployment/1051/
![image](https://user-images.githubusercontent.com/5023186/36759404-7d089858-1bd4-11e8-9ee0-e1a914187dfb.png)

**Comment by Elijahwalkerwest** [comment]
Resolved with sandbox updates.

**Comment by Elijahwalkerwest** [comment]
However results are still not included, give me a minute.

**Comment by Elijahwalkerwest** [comment]
Currently it's not designed to populate Results in editing deployment, since it assumes you are editing details about the deployment, rather than its results. 

Would you like me to change this?

**Comment by AmberSJones** [comment]
Yes, we need to be able to edit the Results in this case. 

There is also a problem in which I am editing (not creating) a site visit and attempting to add a deployment and Results are not available to add.

**Comment by Elijahwalkerwest** [comment]
Alright, have a solution to this. It involved re-designing some things,  but it should work real happy now.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing via PR #265

**Comment by Elijahwalkerwest** [comment]
Deployed and ready to test!

**Comment by AmberSJones** [comment]
The equipment is now selected, but there is nothing regarding results displayed.
![image](https://user-images.githubusercontent.com/5023186/38041754-ce79dd62-326f-11e8-907b-77ce3afa0243.png)

**Comment by Elijahwalkerwest** [comment]
Sigh, small dumb mistake, capitalized a word that wasn't supposed to be, fixed and pushing soon.

**Comment by Elijahwalkerwest** [comment]
Ready to test

**Comment by AmberSJones** [comment]
This is addressed - except for one detail. For the third result, there are no units selected. There should be units pre-selected.

http://django.uwrl.usu.edu/equipment/actions/create-action/instrumentdeployment/1051/
![image](https://user-images.githubusercontent.com/5023186/38116316-c6c1e2ba-336c-11e8-8bf2-b7f3b1dc3141.png)

**Comment by Elijahwalkerwest** [comment]
I need to know how you created that result. It was created with the Unit "Percent" which is not a valid unit for that IOV. As far as I can see the filtering is working fine, and I have no idea how that result was created with that Unit.

**Comment by Elijahwalkerwest** [comment]
I've been trying to re-create this and have been so far unable to. Any further details would be helpful.

**Comment by Elijahwalkerwest** [comment]
It seems this is an artifact of old data. Perhaps at one time Percent was a valid unit for that Equipment Model, but no longer is, this is reflected by that not being populated. 

Closing
