### ISSUE TITLE
Issue adding and updating results

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#266]
Was unable to add further results past the first. 

Resolved in PR #265

**Comment by Elijahwalkerwest** [comment]
Deployed and ready to test!

**Comment by AmberSJones** [comment]
Cannot test because cannot currently add results.

**Comment by Elijahwalkerwest** [comment]
Ready to test

**Comment by AmberSJones** [comment]
I think this is addressed.
