### ISSUE TITLE
Results for nested actions not appearing

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#267]
Any nested actions would not show the results table, and would not allow you to add it. 

Resolved in PR #265

**Comment by Elijahwalkerwest** [comment]
Deployed and ready to test!

**Comment by AmberSJones** [comment]
Unsure what to test here. I would not expect to see nested actions in the Results table, nor to see Results in the nested actions table?

**Comment by Elijahwalkerwest** [comment]
To clarify, I meant results table would not populate for any action past the first in a site visit form.

**Comment by AmberSJones** [comment]
Ok - I think this is addressed.
