### ISSUE TITLE
Instrument Deployment actions past the first would not filter properly. 

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#268]
No filtering based on equipment used on actions past the first. 

Resolved in PR #265

**Comment by Elijahwalkerwest** [comment]
Deployed and ready to test!

**Comment by AmberSJones** [comment]
I need more information on what to test for this issue.

**Comment by Elijahwalkerwest** [comment]
Sorry, to clarify, if a site visit has multiple instrument deployments, only the first one would filter the instrument output variables based on what equipment you selected.
