### ISSUE TITLE
Instrument OUtput variable allowed to be blank, and would delete result if submitted as such.

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#269]
The form never required Instrument Output Variable (Even though the Javascript side did) meaning you could submit with nothing in that field. This would cause the result to be deleted entirely. 

Resolved in PR #265

**Comment by Elijahwalkerwest** [comment]
Deployed.

**Comment by AmberSJones** [comment]
Cannot test this because I cannot add results currently.

**Comment by AmberSJones** [comment]
Currently giving error.

Editing site visit to set IOV to blank (which it shouldn't be):
![image](https://user-images.githubusercontent.com/5023186/38054436-3141d76e-3294-11e8-96ac-2456eb0c479d.png)


![image](https://user-images.githubusercontent.com/5023186/38054411-1ea094f6-3294-11e8-8985-d19eddd4baa2.png)

**Comment by Elijahwalkerwest** [comment]
Resolved. Had to re-design how it got the data from the form and populated it. Much cleaner now! Will push soon.

**Comment by AmberSJones** [comment]
Still getting error on this.

**Comment by Elijahwalkerwest** [comment]
Small oversight, I re-broke it when I fixed something else, got it fixed, pushing soon.

**Comment by AmberSJones** [comment]
I think this is addressed.
