### ISSUE TITLE
Error when trying to retrieve from Deployment Details

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#272]
I am sometimes encountering an error when trying to retrieve from the deployment details page. This is not consistent - I'm not sure if there is something wrong with these deployments?
http://django.uwrl.usu.edu/equipment/actions/create-retrieval/from_deployment/1064/
![image](https://user-images.githubusercontent.com/5023186/38040351-916cd1a2-326c-11e8-86dc-8fb297ec9d62.png)
http://django.uwrl.usu.edu/equipment/actions/create-retrieval/from_deployment/1003/
![image](https://user-images.githubusercontent.com/5023186/38040512-e8b8c240-326c-11e8-84cc-0b8b5ba78bfd.png)

**Comment by Elijahwalkerwest** [comment]
Yeah, it looks like there's a problem with the deployment. Other retrievals work, it looks like no results were created for those deployments somehow.

**Comment by AmberSJones** [comment]
So ... no fix for this issue? Chalking it up to getting fixed when connecting to a "clean" database?

**Comment by Elijahwalkerwest** [comment]
Looks like a bad bit of data where it sometime in the past had been created with two equipments associated with the one deployment. That shouldn't be allowed to happen anymore with some of the recent fixes, this is OK to close.
