### ISSUE TITLE
Unable to Add Results

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#273]
I am trying to create an instrument deployment. I expect the option to add Results to show up, but it is nowhere to be seen.
![image](https://user-images.githubusercontent.com/5023186/38040777-7b031510-326d-11e8-946f-0c46a803c97c.png)

**Comment by AmberSJones** [comment]
Now I have seen some cases where I am able to add Results. It is totally inconsistent. In the below screenshot, the first Instrument Deployment Action does not have Results, but the second Instrument Deployment Action does.
![image](https://user-images.githubusercontent.com/5023186/38043695-108d27cc-3275-11e8-94b2-662ab799eb73.png)

**Comment by Elijahwalkerwest** [comment]
Got it resolved. I missed this case in my testing, will push shortly.

**Comment by AmberSJones** [comment]
The original behavior is addressed, but now we have extra results blocks being added to instrument deployment action creation under a site visit.
![image](https://user-images.githubusercontent.com/5023186/38054291-c0f90cfc-3293-11e8-8fe0-f4391803e7a1.png)

**Comment by Elijahwalkerwest** [comment]
Fixed, pushing soon.

**Comment by Elijahwalkerwest** [comment]
Ready to test.

**Comment by AmberSJones** [comment]
This is addressed.
