### ISSUE TITLE
Unable to Create/Edit Site Visit that Includes Instrument Deployment

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#274]
I'm not sure if this is directly related, but in trying to test this issue, I'm experiencing errors creating/editing site visits. These cases included instrument deployment actions with some results as well as an equipment deployment and a few other actions.

image
![image](https://user-images.githubusercontent.com/5023186/38043834-5c51ce6a-3275-11e8-9f3e-16125f7569be.png)
![image](https://user-images.githubusercontent.com/5023186/38043842-61ca3418-3275-11e8-9894-14c03ce3efc5.png)

image

**Comment by Elijahwalkerwest** [comment]
Ready to test

**Comment by AmberSJones** [comment]
Appears to be addressed.
