### ISSUE TITLE
Site Visit Date Times should restrict Child Action Date Times

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#28]
Should a deployment begin date be the same date as the site visit that the deployment occurred? Also, why is there no time on the Deployment begin date?

**Comment by AmberSJones** [comment]
For the django version, we need to enforce that times for child actions stay within the begin/end times for the parent site visit.

**Comment by AmberSJones** [comment]
Testing the new add point form. Currently, the times of child actions are permitted to be outside of the begin/end date times for the parent action (site visit). We need to restrict it so that the children actions are within the parent begin/end times.

**Comment by marioscience** [comment]
This is done.

**Comment by AmberSJones** [comment]
This is addressed. Closing.
