### ISSUE TITLE
When updating Site Visit, Instrument output variable not shown in summary for Instrument calibration

### ISSUE THREAD

**Issue by Elijahwalkerwest** [UCHIC/ODM2Sensor#283]
When you have an Instrument Calibration, it won't show the IOV in the summary page of a site visit.

**Comment by Elijahwalkerwest** [comment]
Sorry, to clarify, when creating or updating a site visit that includes an instrument calibration action.

**Comment by AmberSJones** [comment]
Is this what you are referring to? The variable is displayed when editing, but not on the Calibration summary view.

![image](https://user-images.githubusercontent.com/5023186/38528480-2dfa6336-3c1d-11e8-8d49-2bd688d34372.png)


![image](https://user-images.githubusercontent.com/5023186/38528462-15486522-3c1d-11e8-8935-36ba3fb3025f.png)

**Comment by Elijahwalkerwest** [comment]
In the calibration details as well as the summary after you finish editing. About to commit and push a fix for both.

**Comment by AmberSJones** [comment]
This appears to be addressed.
