### ISSUE TITLE
Deleting a deployment

### ISSUE THREAD

**Issue by Maurier** [UCHIC/ODM2Sensor#38]
When deleting a deployment, do we need to delete all DeploymentMeasuredVariables associated with it? Keep in mind that a Calibration might be associated with this DeploymentMeasuredVariables and would need to be deleted too.

**Comment by AmberSJones** [comment]
This is a workflow that we need to support in the django version as well. I won't add it to the first version (at least not yet!)

**Comment by Elijahwalkerwest** [comment]
This is implemented alongside deleting an action.

**Comment by AmberSJones** [comment]
This seems to be working well. I'm wondering- if a deployment is deleted that has result associated with it, are the results also deleted?
