### ISSUE TITLE
Better Handling for Calibrations for Multiple Standards

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#69]
We need to think about how to better handle calibrations that involve two or three calibration standards (e.g., pH). It is onerous to expect a user to enter a new calibration for each of the standards used. I'm thinking an implementation similar to the repeatable variables that we're using on ckan.

**Comment by AmberSJones** [comment]
This has been handled in the schema, so I could close the issue. However, we need to make sure that it is properly executed when we add a Calibration Action- we need to be able to use multiple calibration standards/reference materials.

**Comment by marioscience** [comment]
I implemented a multiple select showing all Reference Material instances. Calibration Standards are created with the reference materials selected and the action being created. Please check this functionality in the sandbox to see if it is implemented correctly.

**Comment by AmberSJones** [comment]
This seems to be correctly implemented with the multiple calibration reference material selection. Closing the issue.
