### ISSUE TITLE
'Add New Site Visit' button on Site Visit Details page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#70]
The technicians have requested the addition of an 'Add New Site Visit' button on the Site Visit Details page. This will facilitate the addition of multiple site visits at once. When implemented, it should auto-populate the site information from the site visit from which it was created.

**Comment by AmberSJones** [comment]
This button is present, but not functional yet. I'm putting this on the django version.

**Comment by marioscience** [comment]
A button was added under the map in the detail pages.

**Comment by AmberSJones** [comment]
Great.
