### ISSUE TITLE
Auto-population on Create New Calibration form

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#73]
There is an opportunity to streamline the creation of a calibration by auto-populating some of the fields on the Create New Calibration form:
1. The 'Deployed Equipment' field should populate with the equipment deployed at the site when the site visit occurred.
2. The 'Measured Variable' field should populate with the variable(s) associated with the equipment selected.

**Comment by AmberSJones** [comment]
These are probably features that we can/should implement on the django version as well. I won't add it to the first milestone ... yet.

**Comment by jcaraballo17** [comment]
This issue has been resolved by #134 and #117
