### ISSUE TITLE
Buttons not aligned

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#76]
Buttons are not aligned on the Site Visit detail page:
![image](https://cloud.githubusercontent.com/assets/5023186/7126949/24ba103e-e1fb-11e4-8762-22f01842df91.png)

Also on Deployment detail page:
![image](https://cloud.githubusercontent.com/assets/5023186/7127376/883fe084-e200-11e4-9fa1-c5f1d7989f7c.png)

**Comment by marioscience** [comment]
This issue is fixed.

**Comment by AmberSJones** [comment]
Great.
