### ISSUE TITLE
Next & Previous buttons should be made functional

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#78]
All cases of Next and Previous buttons should be made functional

![image](https://cloud.githubusercontent.com/assets/5023186/7127051/2b57aa2c-e1fc-11e4-8eee-361fd2f44be2.png)

**Comment by marioscience** [comment]
All instances of next an previous are now working.

**Comment by AmberSJones** [comment]
I may not have been clear about how this should be implemented- the buttons should only scroll through actions of that type at the particular site. So, for site visits, it should scroll through the site visits at a site.

Currently, it's scrolling through all site visits in the database.

**Comment by marioscience** [comment]
This change was implemented.

**Comment by AmberSJones** [comment]
This still isn't behaving as I would expect. Let me know if the desired functionality is unclear.

**Comment by marioscience** [comment]
I'm sorry, I just deployed this change to the sandbox server. Sometimes I put a comment to track my progress and the ReadyForTesting label when it is deployed in the sandbox.

**Comment by AmberSJones** [comment]
Great, closing.
