### ISSUE TITLE
Field Activity from Site Visit incorrect

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#79]
Clicking on a Field Activity from a Site Visit detail page brings up the same details as for the Site Visit.

**Comment by AmberSJones** [comment]
I think this is working correctly now? However, instead of displaying 'Field Activity details', we should just display 'Action Details' or 'Calibration Details' specific to the type of action that is being displayed.

Here is what is displayed when a related action is linked to from the Site Visit page:
![image](https://cloud.githubusercontent.com/assets/5023186/8065709/81e43dee-0ea0-11e5-914c-2b3a017ccd6f.png)

Here is the same action with its calibration details delineated:
![image](https://cloud.githubusercontent.com/assets/5023186/8065743/b8f4efcc-0ea0-11e5-96d0-573633c7adab.png)

They should be the same (the second one).

**Comment by marioscience** [comment]
Implemented this. Right now, if the action is a calibration or a deployment it will go to those detail pages.

**Comment by AmberSJones** [comment]
This is working. However, anytime I try to click an Instrument Calibration for a Logan River site, I get a 404 Error. For example, http://django.uwrl.usu.edu/equipment/site-visits/calibration-detail/747/. Any ideas?

**Comment by AmberSJones** [comment]
This appears to be addressed. Closing.
