### ISSUE TITLE
Owner Needs to Be Full Name

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#81]
In all cases where 'Owner' is displayed, it should display the full name. Most cases do, but on the Deployment Details page, only the first name is shown:
![image](https://cloud.githubusercontent.com/assets/5023186/7127164/699dfaba-e1fd-11e4-811a-0ee4d8c21833.png)

**Comment by marioscience** [comment]
Last name was added were it was missing.
