### ISSUE TITLE
Some cases of incorrect related actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#85]
Here's another case of actions incorrectly related:
Site Visit: http://django.uwrl.usu.edu/equipment/visit-detail/174/ clicked on a 'Calibration' field activity and linked to a 'Deployment': http://django.uwrl.usu.edu/equipment/field-activity-detail/723/

**Comment by AmberSJones** [comment]
These are still problematic.

**Comment by marioscience** [comment]
It was showing MethodTypeCV instead of ActionTypeCV. I changed the action type in the field activity and now it looks correct, the method that it is associated with is of type deployment.

**Comment by AmberSJones** [comment]
Ok, great. I think this is working. Closing.
