### ISSUE TITLE
Updated List of Fields for All List and Detail Views

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#89]
As I reviewed the list and detail views, there were a number of fields that did not need to be included, as well as some fields that should be included- from our new schema. I determined to create a list of what we actually want to display. I'm thinking I will put this list into a spreadsheet and send it. @horsburgh , you may have feedback on the fields, so we can revise if needed/desired. Any thoughts, @marioscience ?

**Comment by AmberSJones** [comment]
I think this has been addressed @marioscience ? Is this complete?

**Comment by marioscience** [comment]
Yes. I went trhough the list and changed the fields accordingly. Please let me know if there are any changes you need from there.

**Comment by AmberSJones** [comment]
I'll close this. If anything additional is needed, we'll address it separately.
