### ISSUE TITLE
Implement Addition of Nested Actions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#96]
One of our biggest goals for this release is the implementation of nested actions. The goal is for a user to be able to add a parent action (Site Visit), and then add multiple related children actions on the same edit page. The power point mockups that have been sent out include examples and notes describing many of the specific rules, etc. for each field.

This may include the nesting of additional fields as well- e.g., there should be functionality to add equipment to an action. However, we need to limit the levels of nesting... I think we discussed 4 levels at one point.

**Comment by AmberSJones** [comment]
I think we're about at the point where we can just close this issue. @jcaraballo17 , what do you think?

**Comment by ZachYoshikawa** [comment]
@AmberSJones Juan is subscribed to receive notifications, but does not get them (might be in his spam folder or something). So if @jcaraballo17 doesn't respond on here, I email him.

**Comment by AmberSJones** [comment]
Thanks @ZachYoshikawa . Will do.

**Comment by jcaraballo17** [comment]
Yes, I believe this issue can be closed.
