### ISSUE TITLE
Implement Editing Pages that are (relatively) unchanged from the drupal system

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#97]
I've reviewed the old equipment management interface and identified the editing pages that will NOT change and which you can replicate in your new development: 

- [x] New Site
- [x] New Factory Service Event (note that this is 'Maintenance Action' in the new schema)
- [x] New Equipment Model
- [x] New Equipment
- [x] New Calibration Standard (note that this is 'Reference Material' in the new schema)

-New Site Type
-New Equipment Type
- [x] New Person
- [x] New Vendor (note that this is 'Organization' in the new schema)

**Comment by marioscience** [comment]
These forms were done. They work for both creation and edition of their objects. Please let me know of any changes needed.

**Comment by AmberSJones** [comment]
A few changes need to be made:

New Site Page:
- [ ] Change Elevation to 'Elevation (m)'
- [ ] Change Latitude and Longitude to 'Latitude (dec deg)' and 'Longitude (dec deg)'
- [ ] SiteType, ElevationDatum, and GeoType need to come from the associated vocabularies

Create Factory Service:
- [ ] Implement the fields displayed for Equipment as implemented in the Site Visit form

Create Equipment Model:
- [ ] Implement file selection of the 'Specifications File'

Create Equipment:
- [ ] Equipment Type should come from a vocabulary
- [ ] I get 500 Error when trying to create Equipment

Create Calibration Standard:
- [ ] Change Variables to 'Variable'
- [ ] Add Accuracy
- [ ] Add ability to load a certificate file for ReferenceMaterialCertificateLink

- [ ] Create Site Type: need to be able to add SiteTypes- maybe don't need a form, could be implemented on the Create Site form.
- [ ] Create Equipment Type: need to be able to add EquipmentTypes- maybe don't need a form, could be implemented on the Create Equipment page.

Create New Organization
- [ ] Change to 'Create Organization' rather than 'Create Vendor'
- [ ] Make Organization Type selectable from the controlled vocab

**Comment by AmberSJones** [comment]
This issue has been broken out into others (thanks @jcaraballo17 for doing this!), so I'm closing.
